geekshop/authapp/urls.py
from django.urls import path
from . import views

app_name = 'authapp'

urlpatterns = [

    # http://127.0.0.1:8000/auth redirect to auth/login
    path('', views.redirect_to_login, name='index'),

    # http://127.0.0.1:8000/auth/login
    path('login/', views.login, name='login'),

    # http://127.0.0.1:8000/auth/logout
    path('logout/', views.logout, name='logout'),

    # http://127.0.0.1:8000/auth/edit
    path('edit/', views.edit, name='edit'),  # edit user data

    # http://127.0.0.1:8000/auth/register
    path('register/', views.register, name='register'),  # register new user
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp

from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', mainapp.index, name='main'),
    path('products/', mainapp.products, name='products'),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('admin/', admin.site.urls),

    path('shop/', include('mainapp.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

geekshop/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    # http://127.0.0.1:8000/shop/
    path('',views.categories, name='categories'),

    # http://127.0.0.1:8000/shop/category/pechenki or chai (any category_slug)
    path('category/<slug:category_slug>/', views.products_list, name='products'),

    # http://127.0.0.1:8000/shop/product/1 or 2 or any number
    path('product/<int:product_id>/', views.product_details, name='product_details'),

]

geekshop/mainapp/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Имя')
    slug = models.SlugField(max_length=100, db_index=True, unique=True, verbose_name='Ссылка')

    class Meta:
        ordering = ['name']
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='products',
                                 verbose_name='Категория'
                                 )

    name = models.CharField(max_length=100, db_index=True, verbose_name='Имя')
    slug = models.SlugField(max_length=100, db_index=True, verbose_name='Ссылка')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return self.name

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest
from .models import Product, Category
import datetime
import json

now = datetime.datetime.now()
cur_year = now.year

def index(request:HttpRequest):
    ctx = {'page_title':'гЛаВная',
           'slider_big_text':'удобные стулья',
           'date':cur_year,
           }
    return render(request, 'mainapp/index.html', ctx)

def products(request:HttpRequest):
    links = ['все','дом','офис','модерн','классика']
    ctx = {'page_title':'каТалоГ',
           'links':links,
           'date': cur_year,
           }
    return render(request, 'mainapp/products.html', ctx)

def contacts(request:HttpRequest):
    with open ('static/docs/location.json') as data:
        locations = json.load(data)

    ctx = {'page_title':'кОнтактЫ',
           'date': cur_year,
           'locations':locations,
           }
    return render(request, 'mainapp/contacts.html', ctx)


def categories(request:HttpRequest):
    categories = Category.objects.all()
    ctx = {'categories': categories}
    return render(request, 'mainapp/shop/categories.html', ctx)

def products_list(request:HttpRequest, category_slug=None):
    category = get_object_or_404(Category,slug=category_slug)
    products_list = Product.objects.filter(category=category)
    ctx = {'products_list': products_list, 'category':category}
    return render(request, 'mainapp/shop/products_list.html', ctx)

def product_details(request:HttpRequest, product_id=None):
    product = get_object_or_404(Product,id=product_id)
    ctx = {'product': product}
    return render(request,'mainapp/shop/product_details.html', ctx)

geekshop/mainapp/templates/mainapp/shop/categories.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>categories</title>

</head>
<body>

<h1>Welcome to our shop!</h1>
    <h3>Please, choose category.</h3>
    <ul>
        {% for category in categories %}
            <li>category name: {{ category.name }},
                category slug: {{ category.slug}},
                <p><a href="{% url 'shop:products' category.slug %}">show all products in {{ category.name }}</a></p>
            </li>
        {% endfor %}
    </ul>

    <p><a href="{% url 'main' %}">GO TO MAIN PAGE</a></p>

</body>
</html>

geekshop/mainapp/templates/mainapp/shop/product_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ product.name }}</title>
</head>
<body>
    <h1>{{ product.name }}</h1>
    <p>slug : {{ product.slug }}</p>
    <img src="{{ MEDIA_URL }}{{ product.image }}" alt="{{ product.name }}">
    <p>price: {{ product.price }} RUB</p>
    <p>quantity: {{ product.stock }} </p>
    <p><a href="{% url 'shop:categories' %}">Back to categories</a></p>
    <p><a href="{% url 'main' %}">GO TO MAIN PAGE</a></p>

    <h3>description</h3>
    <p>{{ product.description }}</p>
</body>
</html>

geekshop/mainapp/templates/mainapp/shop/products_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ category.name }}</title>
</head>
<body>
    <h1>Welcome to Products list!</h1>
    <h3>You are in {{ category.name }} category</h3>

    <ul>
        {% for product in products_list %}
            <li>{{ product.name }}
                <a href="{% url 'shop:product_details' product.id %}">product details...</a>
            </li>
        {% endfor %}
    </ul>

</body>
</html>