geekshop/authapp/urls.py
from django.urls import path
from . import views

app_name = 'authapp'

urlpatterns = [

    # http://127.0.0.1:8000/auth redirect to auth/login
    path('', views.redirect_to_login, name='index'),

    # http://127.0.0.1:8000/auth/login
    path('login/', views.login, name='login'),

    # http://127.0.0.1:8000/auth/logout
    path('logout/', views.logout, name='logout'),

    # http://127.0.0.1:8000/auth/edit
    path('edit/', views.edit, name='edit'),  # edit user data

    # http://127.0.0.1:8000/auth/register
    path('register/', views.register, name='register'),  # register new user
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp

from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', mainapp.index, name='main'),
    path('products/', mainapp.products, name='products'),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('admin/', admin.site.urls),

    path('shop/', include('mainapp.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

geekshop/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    # http://127.0.0.1:8000/shop/
    path('',views.categories, name='categories'),

    # http://127.0.0.1:8000/shop/category/pechenki or chai (any category_slug)
    path('category/<slug:category_slug>/', views.products_list, name='products'),

    # http://127.0.0.1:8000/shop/product/1 or 2 or any number
    path('product/<int:product_id>/', views.product_details, name='product_details'),

]

geekshop/mainapp/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Имя')
    slug = models.SlugField(max_length=100, db_index=True, unique=True, verbose_name='Ссылка')

    class Meta:
        ordering = ['name']
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='products',
                                 verbose_name='Категория'
                                 )

    name = models.CharField(max_length=100, db_index=True, verbose_name='Имя')
    slug = models.SlugField(max_length=100, db_index=True, verbose_name='Ссылка')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return self.name

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest
from .models import Product, Category
import datetime
import json

now = datetime.datetime.now()
cur_year = now.year

def index(request:HttpRequest):
    ctx = {'page_title':'гЛаВная',
           'slider_big_text':'удобные стулья',
           'date':cur_year,
           }
    return render(request, 'mainapp/index.html', ctx)

def products(request:HttpRequest):
    links = ['все','дом','офис','модерн','классика']
    ctx = {'page_title':'каТалоГ',
           'links':links,
           'date': cur_year,
           }
    return render(request, 'mainapp/products.html', ctx)

def contacts(request:HttpRequest):
    with open ('static/docs/location.json') as data:
        locations = json.load(data)

    ctx = {'page_title':'кОнтактЫ',
           'date': cur_year,
           'locations':locations,
           }
    return render(request, 'mainapp/contacts.html', ctx)


def categories(request:HttpRequest):
    categories = Category.objects.all()
    ctx = {'categories': categories}
    return render(request, 'mainapp/shop/categories.html', ctx)

def products_list(request:HttpRequest, category_slug=None):
    category = get_object_or_404(Category,slug=category_slug)
    products_list = Product.objects.filter(category=category)
    ctx = {'products_list': products_list, 'category':category}
    return render(request, 'mainapp/shop/products_list.html', ctx)

def product_details(request:HttpRequest, product_id=None):
    product = get_object_or_404(Product,id=product_id)
    ctx = {'product': product}
    return render(request,'mainapp/shop/product_details.html', ctx)

geekshop/mainapp/templates/mainapp/widgets/details_products.html
{% load static %}
<div class="details-products">
			<div class="details-slider">
				<div class="slider-product">
					<img src="{% static 'img/slider1.jpg' %}">
					<img src="{% static 'img/slider1.jpg' %}">
				</div>
				<div class="slider-control">
					<div class="block">
						<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
				</div>
			</div>

			<div class="description">
				<h3 class="big-bold">Отличный стул</h3>
				<h3 class="red">горячее предложение</h3>
				<p class="price"> 2585.9 <span>руб</span></p>
				<a href="#" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					<p>Расположитесь комфортно.</p>
					<p>Отличное качество материалов
					позволит вам это.</p>
					<p>Различные цвета</p>
					<p>высочайший уровень
					эргономики и прочность.</p>
				</div>
			</div>
		</div>

geekshop/mainapp/templates/mainapp/widgets/header.html
<div class="header clearfix">
	<a href="/" class="logo"></a>
	<ul class="menu">
		<li><a href="{% url 'main' %}" class="active">домой</a></li>
		<li><a href="{% url 'products' %}">продукты</a></li>
		<li><a href="{% url 'contacts' %}">контакты</a></li>
		<li><a href="{% url 'shop:categories' %}">новый каталог</a></li>

	</ul>
	<a href="#" class="search"></a>
	<a href="#" class="basket"></a>
</div>

geekshop/mainapp/templates/mainapp/widgets/items.html
{% load static %}
<div class="related">
			<div class="title clearfix">
				<h2>Каталог</h2>
				<a class="explore" href="{% url 'products:products' %}">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>
			<div class="related-products clearfix">

				{% for product in same_products %}
					<div class="block">
						<a href="{% url 'mainapp:details' id=product.id %}"><img src="{{ MEDIA_URL }}{{ product.image }}" alt="{{ product.name }}">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>продукт: {{ product.name }}</h4>
								<p>категория: {{ product.category.name }} </p>

                                <p>цена: {{ product.price }} руб</p>
                                <p>на складе: {{ product.stock }} шт</p>
							</div>
						</a>
					</div>
				{% endfor %}

			</div>
		</div>

geekshop/mainapp/templates/mainapp/widgets/links_clearfix.html
<div class="links clearfix">
	<ul class="links-menu">
		<li>
			<a href="{% url 'mainapp:products' %}">all
			</a>
		</li>
		{% for category in links %}
			<li>
				<a href="{% url 'mainapp:products' category.id %}"
							class="{% if request.resolver_match.kwargs.pk|add:'0' == category.pk %}
										active
									{% endif %}">{{ category.name }}
				</a>
			</li>
		{% endfor %}

	</ul>
</div>

geekshop/mainapp/templates/mainapp/widgets/location.html
<div class="location">
    {% for location in locations %}
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>{{ location.city }}</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>{{ location.phone_number }}</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>{{ location.email }}</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>{{ location.address }}</p>
            </div>
        </div>
    {% endfor %}


</div>

geekshop/mainapp/templates/mainapp/widgets/related.html
{% load static %}
<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>
			<div class="related-products clearfix">
				<div class="block">
					<a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/product-31.jpg" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>

			</div>
		</div>

geekshop/mainapp/templates/mainapp/widgets/text_slider.html
{% load static %}
<div class="text-slider">
            <h3 class="green">тенденции</h3>
			<h3 class="big">
				{% if slider_big_text %}
					{{ slider_big_text|upper }}
				{% else %}
					Добро пожаловать!
				{% endif %}
			</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>